// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPd1caI46MI4qgdeIPYJ5GAjZDDvwQT08',
    appId: '1:77868161415:web:f30e5bb8ad43d2a9445b22',
    messagingSenderId: '77868161415',
    projectId: 'tugon-4e318',
    authDomain: 'tugon-4e318.firebaseapp.com',
    storageBucket: 'tugon-4e318.firebasestorage.app',
    measurementId: 'G-YG33WNW1N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCidUjDHIkYTvxIrYdoNI80xM6ss0qhZsY',
    appId: '1:77868161415:android:09375a0ef02c1d2d445b22',
    messagingSenderId: '77868161415',
    projectId: 'tugon-4e318',
    storageBucket: 'tugon-4e318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLhuIwKNTbXE4T-3NKeBa9-N9aSb0ly08',
    appId: '1:77868161415:ios:74559b155e558c48445b22',
    messagingSenderId: '77868161415',
    projectId: 'tugon-4e318',
    storageBucket: 'tugon-4e318.firebasestorage.app',
    androidClientId: '77868161415-8olvqege0t9vl4qcoq8tg3cup0f91icv.apps.googleusercontent.com',
    iosClientId: '77868161415-2vdkqnu1qs91aflp4c4nevq335cs7rkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLhuIwKNTbXE4T-3NKeBa9-N9aSb0ly08',
    appId: '1:77868161415:ios:74559b155e558c48445b22',
    messagingSenderId: '77868161415',
    projectId: 'tugon-4e318',
    storageBucket: 'tugon-4e318.firebasestorage.app',
    androidClientId: '77868161415-8olvqege0t9vl4qcoq8tg3cup0f91icv.apps.googleusercontent.com',
    iosClientId: '77868161415-2vdkqnu1qs91aflp4c4nevq335cs7rkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPd1caI46MI4qgdeIPYJ5GAjZDDvwQT08',
    appId: '1:77868161415:web:569b61ad5db85885445b22',
    messagingSenderId: '77868161415',
    projectId: 'tugon-4e318',
    authDomain: 'tugon-4e318.firebaseapp.com',
    storageBucket: 'tugon-4e318.firebasestorage.app',
    measurementId: 'G-S3PKFH2GN3',
  );
}
